import type { Candidate, Conversation, Filters, Owner, Pet } from "./types";

/* Warm gradient placeholders used across the mocks in place of real photos. */
export const GRADIENTS = {
  peachGold: "linear-gradient(135deg,#F5BFA6,#E8A93C)",
  coralRust: "linear-gradient(135deg,#EF9E7B,#C44F2C)",
  coralWarm: "linear-gradient(135deg,#EF9E7B,#E97E54)",
  sandGold: "linear-gradient(135deg,#F5D08A,#E8A93C)",
  sandCoral: "linear-gradient(135deg,#F5D08A,#E97E54)",
  taupe: "linear-gradient(135deg,#C5B4A2,#7F6C58)",
};

export const seedOwner: Owner = {
  name: "ნიკა",
  location: "თბილისი, საქართველო",
  about: "ცხოველების მოყვარული, ლუნას მფლობელი. ვეძებ საიმედო და ჯანმრთელ პარტნიორს.",
  verification: "verified",
};

export const seedPets: Pet[] = [
  {
    id: "luna",
    name: "ლუნა",
    species: "cat",
    breed: "ბრიტანული მოკლებეწვიანი",
    gender: "female",
    birthLabel: "მარტი 2024",
    ageYears: 2,
    photos: [
      { gradient: GRADIENTS.peachGold, emoji: "🐈" },
      { gradient: GRADIENTS.coralWarm, emoji: "🐈" },
      { gradient: GRADIENTS.sandGold, emoji: "🐾" },
    ],
    bio: "მეგობრული და მოსიყვარულე კატა, უყვარს თევზი და გრძელი ძილი მზეზე ☀️",
    health: { vaccinated: true, tested: true, docs: false },
    healthTags: ["ვაქცინირებული", "დეჰელმინთიზაცია"],
    intent: "mate",
    verified: true,
  },
  {
    id: "bobi",
    name: "ბობი",
    species: "dog",
    breed: "ლაბრადორი",
    gender: "male",
    birthLabel: "ივნისი 2022",
    ageYears: 4,
    photos: [{ gradient: GRADIENTS.taupe, emoji: "🐕" }],
    bio: "ენერგიული და ერთგული ლაბრადორი, უყვარს გასეირნება და თამაში.",
    health: { vaccinated: true, tested: false, docs: true },
    healthTags: ["ვაქცინირებული"],
    intent: "available",
    verified: false,
  },
];

export const seedCandidates: Candidate[] = [
  {
    id: "toma",
    name: "თომა",
    species: "cat",
    breed: "ბრიტანული მოკლებეწვიანი",
    gender: "male",
    birthLabel: "მაისი 2023",
    ageYears: 3,
    photos: [
      { gradient: GRADIENTS.peachGold, emoji: "🐈" },
      { gradient: GRADIENTS.sandGold, emoji: "🐈" },
      { gradient: GRADIENTS.coralWarm, emoji: "🐾" },
    ],
    bio: "მშვიდი და ჯენტლმენი ბრიტანელი. უყვარს ფანჯარასთან ჯდომა, თევზი და გრძელი ძილი. პირველი ნაგავი ჯანმრთელი და აქტიური იყო.",
    health: { vaccinated: true, tested: true, docs: true },
    healthTags: ["ვაქცინა", "ტესტები"],
    intent: "mate",
    verified: true,
    distanceKm: 2.4,
    ownerName: "გიორგი",
    ownerVerified: true,
    mutualLike: true,
  },
  {
    id: "leo",
    name: "ლეო",
    species: "cat",
    breed: "სპარსული",
    gender: "male",
    birthLabel: "თებერვალი 2024",
    ageYears: 2,
    photos: [{ gradient: GRADIENTS.coralRust, emoji: "🐈" }],
    bio: "ენერგიული და ცნობისმოყვარე. სათამაშოების დიდი მოყვარული.",
    health: { vaccinated: true, tested: false, docs: false },
    healthTags: ["ვაქცინა"],
    intent: "mate",
    verified: true,
    distanceKm: 4.1,
    ownerName: "ანა",
    ownerVerified: false,
    mutualLike: false,
  },
  {
    id: "simoni",
    name: "საიმონი",
    species: "cat",
    breed: "მაინკუნი",
    gender: "male",
    birthLabel: "ივლისი 2022",
    ageYears: 4,
    photos: [{ gradient: GRADIENTS.sandCoral, emoji: "🐈" }],
    bio: "დიდი, ფუმფულა და მშვიდი გიგანტი. საუკეთესო კომპანიონი.",
    health: { vaccinated: true, tested: true, docs: false },
    healthTags: ["ვაქცინა", "ჩიპი"],
    intent: "available",
    verified: true,
    distanceKm: 5.7,
    ownerName: "დათო",
    ownerVerified: true,
    mutualLike: false,
  },
  {
    id: "nia",
    name: "ნია",
    species: "cat",
    breed: "ბრიტანული მოკლებეწვიანი",
    gender: "male",
    birthLabel: "ოქტომბერი 2023",
    ageYears: 2,
    photos: [{ gradient: GRADIENTS.taupe, emoji: "🐈" }],
    bio: "მშვიდი ხასიათი, სუფთა წარმომავლობა. კარგად ეწყობა სხვა კატებს.",
    health: { vaccinated: true, tested: false, docs: true },
    healthTags: ["ვაქცინა"],
    intent: "mate",
    verified: false,
    distanceKm: 7.2,
    ownerName: "თამარი",
    ownerVerified: false,
    mutualLike: false,
  },
];

export const seedConversations: Conversation[] = [
  {
    id: "toma",
    candidateId: "toma",
    matchedLabel: "დღეს",
    unread: 2,
    lastTime: "ახლა",
    messages: [
      { id: "m1", from: "them", kind: "text", text: "გამარჯობა! ლუნა ნამდვილად ლამაზია 😍", time: "14:21" },
      { id: "m2", from: "me", kind: "text", text: "მადლობა! თომაც ძალიან მოხდენილია 🙂 სად ხართ?", time: "14:24", read: true },
      { id: "m3", from: "them", kind: "text", text: "ვაკეში. შეგვიძლია ჯერ ვეტერინართან შევხვდეთ, ყველაფერი წესრიგში იყოს.", time: "14:27" },
      { id: "m4", from: "me", kind: "text", text: "შესანიშნავი იდეაა. ორივე ვაქცინირებულია და ტესტებიც გავიარეთ.", time: "14:30", read: true },
      { id: "m5", from: "them", kind: "text", text: "მშვენიერია, მოდი ხვალ ☀️", time: "14:32" },
    ],
  },
  {
    id: "leo",
    candidateId: "leo",
    matchedLabel: "გუშინ",
    unread: 0,
    lastTime: "2 სთ",
    messages: [
      { id: "m1", from: "me", kind: "text", text: "გამარჯობა! ლეო ძალიან საყვარელია 🐾", time: "11:02", read: true },
      { id: "m2", from: "them", kind: "text", text: "წავიდა სასეირნოდ? 🐾", time: "12:40" },
    ],
  },
  {
    id: "simoni",
    candidateId: "simoni",
    matchedLabel: "გუშინ",
    unread: 0,
    lastTime: "გუშინ",
    messages: [
      { id: "m1", from: "them", kind: "text", text: "მადლობა მოწონებისთვის!", time: "18:15" },
    ],
  },
  {
    id: "nia",
    candidateId: "nia",
    matchedLabel: "2 დღის წინ",
    unread: 0,
    lastTime: "2 დღე",
    messages: [],
  },
];

export const defaultFilters: Filters = {
  species: "cat",
  openToCompatibleBreeds: false,
  gender: "male",
  distanceKm: 10,
  ageRange: [1, 6],
  verifiedOnly: true,
};

export const BREEDS: Record<string, string[]> = {
  cat: ["ბრიტანული მოკლებეწვიანი", "სპარსული", "მაინკუნი", "სიამური", "სფინქსი", "შოტლანდიური"],
  dog: ["ლაბრადორი", "გერმანული ნაგაზი", "ჰასკი", "პუდელი", "კავკასიური ნაგაზი"],
  bird: ["ტალღოვანი თუთიყუში", "კორელა", "კანარი"],
  other: ["სხვა"],
};
